#!/bin/bash -e

ORG_PATH="github.com/jonfk"
REPO_PATH="${ORG_PATH}/appliance-management-web"

export GOPATH=${PWD}/gopath

echo $GOPATH

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go build -o bin/appliance-manager ${REPO_PATH}
